### ISSUE TITLE
Unregister when all calls are ended - failed

### ISSUE THREAD

**Issue by smolskyaleksey** [VoIPGRID/VialerSIPLib#27] opened 2016-12-16 11:31 UTC
Accordion Goals spec. Library have to make unregister when all calls are ended.
From log file:
```
2016-12-16 14:26:59:777 FoilChat[2851:662216] No active calls for any account, stopping network monitor
2016-12-16 14:26:59:778 FoilChat[2851:662216] Call(8ACC0643-4B42-4C90-88C1-7E4825C680B6) removed. Calls count: 0
2016-12-16 14:26:59:780 FoilChat[2851:662216]  pjsua_media.c !......Call 0: deinitializing media..
2016-12-16 14:26:59:782 FoilChat[2851:662216]  pjsua_media.c  ........Media stream call00:0 is destroyed
2016-12-16 14:26:59:782 FoilChat[2851:662216]    pjsua_vid.c  ........Stopping video stream..
2016-12-16 14:26:59:805 FoilChat[2851:662216]   darwin_dev.m  .........Stopping Darwin video stream
2016-12-16 14:26:59:868 FoilChat[2851:662216]    pjsua_vid.c  .........Window 1: destroying..
2016-12-16 14:26:59:868 FoilChat[2851:662216]     vid_port.c  ..........Closing Front Camera..
2016-12-16 14:26:59:875 FoilChat[2851:662216] ios_opengl_dev  .........Stopping ios opengl stream
2016-12-16 14:26:59:875 FoilChat[2851:662216]    pjsua_vid.c  .........Window 0: destroying..
2016-12-16 14:26:59:875 FoilChat[2851:662216] ios_opengl_dev  ..........Stopping ios opengl stream
2016-12-16 14:26:59:875 FoilChat[2851:662216]     vid_port.c  ..........Closing OpenGL renderer..
2016-12-16 14:26:59:882 FoilChat[2851:662216]  pjsua_media.c  ........Media stream call00:1 is destroyed
2016-12-16 14:27:00:784 FoilChat[2851:662216]    pjsua_aud.c  Closing sound device after idle for 1 second(s)
2016-12-16 14:27:00:788 FoilChat[2851:662216]    pjsua_aud.c  .Closing iPhone IO device sound playback device and iPhone IO device sound capture device
2016-12-16 14:27:00:806 FoilChat[2851:662216] coreaudio_dev.  .core audio stream stopped
2016-12-16 14:27:01:411 FoilChat[2851:662042] Dealloc Call uuid:8ACC0643-4B42-4C90-88C1-7E4825C680B6 id:0
```

It was lost in Commit:
1c74d89889c03394d1d624070ee52637f606ed64 [1c74d89]

**Comment by bobvoorneveld** [comment] 2016-12-16 12:25
Duplicate of https://github.com/VoIPGRID/VialerSIPLib/issues/28

Closing this issue

**Closed by bobvoorneveld** 2016-12-16 12:25 UTC
Labels: duplicate
